// AUTO-GENERATED by scripts/gen-i18n-registry.mjs. Do not edit by hand.
import ru from "./ru.json";
import kk from "./kk.json";
import en from "./en.json";
import zh from "./zh.json";
import uz from "./uz.json";
import ky from "./ky.json";
import ko from "./ko.json";
import ja from "./ja.json";
import hi from "./hi.json";
import ar from "./ar.json";

export const dictionaries = { ru, kk, en, zh, uz, ky, ko, ja, hi, ar } as const;
export const localeCodes = ["ru","kk","en","zh","uz","ky","ko","ja","hi","ar"] as const;
